version: "3"
services:
  proxy:
    image: traefik:2.3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:8080
      - 80:80
    command:
      - --api.insecure=true
      - --providers.docker.defaultrule=Host(`{{ normalize .Name }}.localhost`)
  api:
    build: ./api
    depends_on:
      - db
    ports:
      - 5000
    volumes:
      - ./api:/usr/local/src
    environment:
      PORT: 5000
      DATABASE_URL: postgres://postgres:123@db/postgres?sslmode=disable
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_CHANNEL: 1096135108932665486
  client:
    build: ./client
    ports:
      - 3000
    volumes:
      - ./client:/usr/local/src
    environment:
      REACT_APP_API_URL: http://api-localthreat.localhost
      CI: "true"
      EXTEND_ESLINT: "true"
  db:
    image: postgres:12.4-alpine
    environment:
      - POSTGRES_PASSWORD=123
